import { conservativeWaterStep, waterStorage } from './transport.js';

const $=id=>document.getElementById(id);
const defaults={nx:20,ny:20,nz:8,steps:90,highPermFraction:.38,permContrast:12,correlation:.62,porosity:.22,mobilityRatio:2,propagation:.35,treatmentStrength:.65,treatmentStep:28,targetPercentile:82,swi:.20,sor:.22,nw:2,no:2,eorType:'polymer',treatmentType:'gel'};
let seed=137,latest=null;
const dirs=[[1,0,0],[-1,0,0],[0,1,0],[0,-1,0],[0,0,1],[0,0,-1]];
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function rng(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296}
function gaussian(){const u=Math.max(rng(),1e-9),v=rng();return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v)}
function idx(x,y,z,p){return x+p.nx*(y+p.ny*z)}
function xyz(i,p){const z=Math.floor(i/(p.nx*p.ny)),r=i-z*p.nx*p.ny,y=Math.floor(r/p.nx),x=r-y*p.nx;return[x,y,z]}
function percentile(a,q){const s=[...a].sort((x,y)=>x-y),i=Math.floor(clamp(q,0,1)*(s.length-1));return s[i]}
function params(){return{nx:+$('nx').value,ny:+$('ny').value,nz:+$('nz').value,steps:+$('steps').value,highPermFraction:+$('highPermFraction').value,permContrast:+$('permContrast').value,correlation:+$('correlation').value,porosity:+$('porosity').value,mobilityRatio:+$('mobilityRatio').value,propagation:+$('propagation').value,treatmentStrength:+$('treatmentStrength').value,treatmentStep:+$('treatmentStep').value,targetPercentile:+$('targetPercentile').value,swi:+$('swi').value,sor:+$('sor').value,nw:+$('nw').value,no:+$('no').value,eorType:$('eorType').value,treatmentType:$('treatmentType').value}}
function smoothField(raw,p,passes){let a=raw.slice();for(let pass=0;pass<passes;pass++){const b=a.slice();for(let z=0;z<p.nz;z++)for(let y=0;y<p.ny;y++)for(let x=0;x<p.nx;x++){let sum=a[idx(x,y,z,p)]*2,w=2;for(const[dX,dY,dZ]of dirs){const X=x+dX,Y=y+dY,Z=z+dZ;if(X>=0&&Y>=0&&Z>=0&&X<p.nx&&Y<p.ny&&Z<p.nz){sum+=a[idx(X,Y,Z,p)];w++}}b[idx(x,y,z,p)]=sum/w}a=b}return a}
function makeGeology(p){const n=p.nx*p.ny*p.nz,raw=Array.from({length:n},()=>gaussian()),passes=Math.round(p.correlation*6),s=smoothField(raw,p,passes),cut=percentile(s,1-p.highPermFraction),k=s.map(v=>v>=cut?p.permContrast:1);for(let i=0;i<n;i++)k[i]*=Math.exp(.18*s[i]);return k}
function spanningCluster(k,p){const threshold=percentile(k,1-p.highPermFraction),active=k.map(v=>v>=threshold),seen=new Uint8Array(k.length),q=[];for(let z=0;z<p.nz;z++)for(let y=0;y<p.ny;y++){const i=idx(0,y,z,p);if(active[i]){seen[i]=1;q.push(i)}}for(let h=0;h<q.length;h++){const i=q[h],[x,y,z]=xyz(i,p);for(const[dX,dY,dZ]of dirs){const X=x+dX,Y=y+dY,Z=z+dZ;if(X<0||Y<0||Z<0||X>=p.nx||Y>=p.ny||Z>=p.nz)continue;const j=idx(X,Y,Z,p);if(active[j]&&!seen[j]){seen[j]=1;q.push(j)}}}let spans=false;for(let z=0;z<p.nz;z++)for(let y=0;y<p.ny;y++)if(seen[idx(p.nx-1,y,z,p)])spans=true;return{mask:seen,spans,threshold,frac:q.length/k.length}}
function processFactors(type){if(type==='polymer')return{mobility:.62,oilGain:1.05};if(type==='co2')return{mobility:1.35,oilGain:1.12};if(type==='foam')return{mobility:.52,oilGain:1.03};return{mobility:1,oilGain:1}}
function relperm(sw,p){const den=Math.max(1-p.swi-p.sor,.05),se=clamp((sw-p.swi)/den,0,1),krw=Math.pow(se,p.nw),kro=Math.pow(1-se,p.no);return{se,krw,kro}}
function totalMob(sw,p,M){const r=relperm(sw,p);return r.kro+M*r.krw}
function fracFlow(sw,p,M){const r=relperm(sw,p),lw=M*r.krw;return lw/Math.max(r.kro+lw,1e-12)}
function pressureSolve(effK,sw,p,M,guess){const n=effK.length,P=guess?Float64Array.from(guess):new Float64Array(n);if(!guess)for(let i=0;i<n;i++){const[x]=xyz(i,p);P[i]=1-x/(p.nx-1)}for(let it=0;it<24;it++){const next=Float64Array.from(P);for(let z=0;z<p.nz;z++)for(let y=0;y<p.ny;y++)for(let x=1;x<p.nx-1;x++){const i=idx(x,y,z,p),li=totalMob(sw[i],p,M);let num=0,den=0;for(const[dX,dY,dZ]of dirs){const X=x+dX,Y=y+dY,Z=z+dZ;if(X<0||Y<0||Z<0||X>=p.nx||Y>=p.ny||Z>=p.nz)continue;const j=idx(X,Y,Z,p),lj=totalMob(sw[j],p,M),ki=effK[i]*li,kj=effK[j]*lj,T=2*ki*kj/Math.max(ki+kj,1e-12);num+=T*P[j];den+=T}if(den>0)next[i]=num/den}for(let z=0;z<p.nz;z++)for(let y=0;y<p.ny;y++){next[idx(0,y,z,p)]=1;next[idx(p.nx-1,y,z,p)]=0}P.set(next)}return P}
function buildFluxes(effK,sw,p,M,pressure){const fluxes=[];for(let z=0;z<p.nz;z++)for(let y=0;y<p.ny;y++)for(let x=0;x<p.nx;x++){const i=idx(x,y,z,p);for(const[dX,dY,dZ]of dirs){const X=x+dX,Y=y+dY,Z=z+dZ;if(X<0||Y<0||Z<0||X>=p.nx||Y>=p.ny||Z>=p.nz)continue;const j=idx(X,Y,Z,p),dp=pressure[i]-pressure[j];if(dp<=0)continue;const li=totalMob(sw[i],p,M),lj=totalMob(sw[j],p,M),ki=effK[i]*li,kj=effK[j]*lj,T=2*ki*kj/Math.max(ki+kj,1e-12),q=T*dp;if(q>1e-14)fluxes.push([i,j,q])}}return fluxes}
function producerFluxes(effK,sw,p,M,pressure){const out=[];for(let z=0;z<p.nz;z++)for(let y=0;y<p.ny;y++){const i=idx(p.nx-1,y,z,p),j=idx(p.nx-2,y,z,p),li=totalMob(sw[i],p,M),lj=totalMob(sw[j],p,M),ki=effK[i]*li,kj=effK[j]*lj,T=2*ki*kj/Math.max(ki+kj,1e-12),q=T*Math.max(pressure[j]-pressure[i],0);out.push([i,q])}return out}
function run(){const p=params();if(p.swi+p.sor>=.9){alert('Swi + Sor must be below 0.90');return}const n=p.nx*p.ny*p.nz,k=makeGeology(p),perc=spanningCluster(k,p),sw=new Float64Array(n).fill(p.swi),treated=new Uint8Array(n),effK=Float64Array.from(k),pv=new Float64Array(n).fill(p.porosity),totalPV=pv.reduce((a,b)=>a+b,0),pf=processFactors(p.eorType),M=p.mobilityRatio*pf.mobility,maxSw=1-p.sor,inlet=[];for(let z=0;z<p.nz;z++)for(let y=0;y<p.ny;y++){const i=idx(0,y,z,p);sw[i]=maxSw;inlet.push(i)}const initialStorage=waterStorage(sw,pv),targetK=percentile(k,p.targetPercentile/100),history=[];let bt=null,pressure=null,cumulativeInjected=0,cumulativeProduced=0,cumulativeResidual=0;
for(let t=0;t<p.steps;t++){
  if(t===Math.min(p.treatmentStep,p.steps-1)&&p.treatmentType!=='none'){for(let i=0;i<n;i++){const r=relperm(sw[i],p);if(perc.mask[i]&&k[i]>=targetK&&r.se>.18){treated[i]=1;const tf=p.treatmentType==='foam'?.75:1;effK[i]*=Math.max(.02,1-p.treatmentStrength*tf)}}pressure=null}
  if(t%3===0||pressure===null)pressure=pressureSolve(effK,sw,p,M,pressure);
  const fluxes=buildFluxes(effK,sw,p,M,pressure),outflows=producerFluxes(effK,sw,p,M,pressure);
  const step=conservativeWaterStep({sw,pv,fluxes,producerOutflows:outflows,fractionalFlow:s=>fracFlow(s,p,M),swi:p.swi,maxSw,inletIndices:inlet,courant:clamp(p.propagation,.05,.8)});sw.set(step.sw);cumulativeInjected+=step.injectedWater;cumulativeProduced+=step.producedWater;cumulativeResidual+=step.residual;
  let qTot=0,qWater=0;for(const[i,q]of outflows){qTot+=q;qWater+=q*fracFlow(sw[i],p,M)}const wc=qTot>0?qWater/qTot:0;if(bt===null&&wc>.10)bt=t;let rf=0,sweep=0;for(let i=0;i<n;i++){const r=relperm(sw[i],p);rf+=(sw[i]-p.swi)/Math.max(1-p.swi,1e-9);sweep+=r.se>.05?1:0}rf=clamp(rf/n,0,.95);sweep/=n;const qo=2200*pf.oilGain*qTot/Math.max(p.ny*p.nz,1)*(1-wc),qw=2200*qTot/Math.max(p.ny*p.nz,1)*wc,storage=waterStorage(sw,pv),waterStoragePvi=(storage-initialStorage)/Math.max(totalPV,1e-12),mbResidualPvi=cumulativeResidual/Math.max(totalPV,1e-12),injectedPvi=cumulativeInjected/Math.max(totalPV,1e-12),producedWaterPvi=cumulativeProduced/Math.max(totalPV,1e-12);history.push({t,qo,qw,wc,rf,sweep,waterStoragePvi,mbResidualPvi,injectedPvi,producedWaterPvi,dt:step.dt})
}
latest={p,k,effK,sw,treated,perc,history,bt,pressure,M,pv,totalPV};render()}

function wellTrace(x,y,p,name,color){return{type:'scatter3d',mode:'lines+markers',x:Array(p.nz).fill(x),y:Array(p.nz).fill(y),z:Array.from({length:p.nz},(_,i)=>i),name,line:{color,width:8},marker:{color,size:3},hovertemplate:`${name}<extra></extra>`}}
function propertyTrace(mode,l){const{p,k,sw,pressure,treated,perc}=l,x=[],y=[],z=[],v=[],text=[];for(let i=0;i<k.length;i++){let include=true,val=0;if(mode==='saturation'){val=sw[i];include=relperm(val,p).se>.015}else if(mode==='permeability')val=Math.log10(k[i]);else if(mode==='pressure')val=pressure?pressure[i]:0;else if(mode==='cluster'){val=perc.mask[i]?1:0;include=!!perc.mask[i]}else{val=treated[i]?1:0;include=!!treated[i]}if(!include)continue;const[X,Y,Z]=xyz(i,p);x.push(X);y.push(Y);z.push(Z);v.push(val);text.push(`I=${X+1}, J=${Y+1}, K=${Z+1}<br>k=${k[i].toFixed(2)} rel.<br>φ=${p.porosity.toFixed(2)}<br>Sw=${sw[i].toFixed(3)}${pressure?`<br>P*=${pressure[i].toFixed(3)}`:''}${treated[i]?'<br>Treated cell':''}`)}
  const colorbarTitle=mode==='permeability'?'log₁₀(k rel.)':mode==='pressure'?'P*':mode==='saturation'?'Sw':mode==='cluster'?'Connected':'Treatment';
  const colorscale=mode==='permeability'?'Viridis':mode==='pressure'?'Cividis':mode==='saturation'?'Turbo':mode==='cluster'?'Blues':'Reds';
  return{type:'scatter3d',mode:'markers',x,y,z,text,hovertemplate:'%{text}<extra></extra>',name:colorbarTitle,marker:{symbol:'square',size:6,color:v,colorscale,opacity:mode==='cluster'||mode==='treatment'?.92:.78,colorbar:{title:colorbarTitle,thickness:14,len:.72}}};
}
function render3D(){if(!latest)return;const mode=$('viewMode').value,p=latest.p,traces=[propertyTrace(mode,latest)];const midY=(p.ny-1)/2;traces.push(wellTrace(0,midY,p,'INJ-01','#30b7ff'));traces.push(wellTrace(p.nx-1,midY,p,'PROD-01','#ffcf4a'));Plotly.react('reservoir3d',traces,{margin:{l:0,r:0,t:8,b:0},paper_bgcolor:'rgba(0,0,0,0)',font:{color:'#dfe9f5',size:11},legend:{x:.01,y:.99,bgcolor:'rgba(8,17,28,.72)'},scene:{xaxis:{title:'I / injector → producer',gridcolor:'#2b425d',zeroline:false},yaxis:{title:'J',gridcolor:'#2b425d',zeroline:false},zaxis:{title:'K layer',autorange:'reversed',gridcolor:'#2b425d',zeroline:false},aspectmode:'manual',aspectratio:{x:1.9,y:1,z:.58},camera:{eye:{x:1.55,y:1.55,z:.9}},bgcolor:'#07111d'}},{responsive:true,displaylogo:false})}
function renderProduction(){const h=latest.history,t=h.map(d=>d.t),qo=h.map(d=>d.qo),wc=h.map(d=>100*d.wc),rf=h.map(d=>100*d.rf),pvi=h.map(d=>100*d.injectedPvi);Plotly.react('productionPlot',[{x:t,y:qo,name:'Oil-rate index',type:'scatter',mode:'lines',line:{width:3}},{x:t,y:wc,name:'Water cut',type:'scatter',mode:'lines',yaxis:'y2'},{x:t,y:rf,name:'Recovery factor',type:'scatter',mode:'lines',yaxis:'y2',line:{dash:'dot'}},{x:t,y:pvi,name:'Injected PV',type:'scatter',mode:'lines',yaxis:'y2',line:{dash:'dash'}}],{margin:{l:58,r:58,t:18,b:48},paper_bgcolor:'rgba(0,0,0,0)',plot_bgcolor:'#07111d',font:{color:'#dfe9f5'},xaxis:{title:'Simulation step',gridcolor:'#20344a'},yaxis:{title:'Relative rate index',gridcolor:'#20344a'},yaxis2:{title:'Percent / %PV',overlaying:'y',side:'right'},legend:{orientation:'h',y:1.13}},{responsive:true,displaylogo:false})}
function render(){const l=latest,h=l.history,last=h[h.length-1];$('rfKpi').textContent=(last.rf*100).toFixed(1)+'%';$('wcKpi').textContent=(last.wc*100).toFixed(1)+'%';$('btKpi').textContent=l.bt===null?'No breakthrough':'Step '+l.bt;$('spanKpi').textContent=l.perc.spans?'Yes':'No';$('mbKpi').textContent=(100*last.mbResidualPvi).toExponential(2)+'%';render3D();renderProduction();const treated=l.treated.reduce((a,b)=>a+b,0);const notes=[['Connectivity',l.perc.spans?`A spanning high-permeability path exists (${(100*l.perc.frac).toFixed(1)}% of cells connected from the injector side).`:'No injector-to-producer spanning high-permeability path was detected.'],['Material balance',`Finite-volume water transport conserves internal transfers explicitly. Cumulative water-balance residual is ${(100*last.mbResidualPvi).toExponential(2)}% PV; injected water is ${(100*last.injectedPvi).toFixed(2)}% PV and produced water is ${(100*last.producedWaterPvi).toFixed(2)}% PV. These are normalized research-model quantities, not field barrels.`],['Conformance',treated?`${treated} cells were treated at step ${l.p.treatmentStep}. Permeability reduction changes transmissibility and the subsequent pressure/transport solution.`:'No conformance treatment was applied.'],['Results workspace','The 3D view now uses simulation-style property rendering with injector/producer trajectories and selectable saturation, pressure, permeability, connectivity and treatment properties. Visuals are generated directly from the current numerical state.']];$('diagnostics').innerHTML=notes.map(([a,b])=>`<div class="insight"><b>${a}</b><p>${b}</p></div>`).join('')}
function wire(){const ranges={highPermFraction:'hpv',permContrast:'pcv',correlation:'scv',porosity:'phiv',mobilityRatio:'mrv',propagation:'ppv',treatmentStrength:'tsv',treatmentStep:'tssv',targetPercentile:'ctv',swi:'swiv',sor:'sorv',nw:'nwv',no:'nov'};function labels(){for(const[k,v]of Object.entries(ranges)){let x=+$(k).value,s=x;if(k==='permContrast')s=x+'×';if(k==='treatmentStrength'||k==='targetPercentile')s=Math.round(x*(k==='treatmentStrength'?100:1))+'%';$(v).textContent=s}}Object.keys(ranges).forEach(k=>$(k).addEventListener('input',labels));$('runBtn').onclick=run;$('newGeoBtn').onclick=()=>{seed=(Date.now()>>>0);run()};$('viewMode').onchange=render3D;$('resetBtn').onclick=()=>{for(const[k,v]of Object.entries(defaults))if($(k))$(k).value=v;labels();seed=137;run()};labels();run()}
wire();
