const $=id=>document.getElementById(id);
const defaults={nx:20,ny:20,nz:8,steps:90,highPermFraction:.38,permContrast:12,correlation:.62,mobilityRatio:2,propagation:.64,treatmentStrength:.65,treatmentStep:28,targetPercentile:82,swi:.20,sor:.22,nw:2,no:2,eorType:'polymer',treatmentType:'gel'};
let seed=137,latest=null;
const dirs=[[1,0,0],[-1,0,0],[0,1,0],[0,-1,0],[0,0,1],[0,0,-1]];
function rng(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296}
function gaussian(){const u=Math.max(rng(),1e-9),v=rng();return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v)}
function idx(x,y,z,p){return x+p.nx*(y+p.ny*z)}
function xyz(i,p){const z=Math.floor(i/(p.nx*p.ny)),r=i-z*p.nx*p.ny,y=Math.floor(r/p.nx),x=r-y*p.nx;return[x,y,z]}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function percentile(a,q){const s=[...a].sort((x,y)=>x-y),i=Math.floor(clamp(q,0,1)*(s.length-1));return s[i]}
function params(){return{nx:+$('nx').value,ny:+$('ny').value,nz:+$('nz').value,steps:+$('steps').value,highPermFraction:+$('highPermFraction').value,permContrast:+$('permContrast').value,correlation:+$('correlation').value,mobilityRatio:+$('mobilityRatio').value,propagation:+$('propagation').value,treatmentStrength:+$('treatmentStrength').value,treatmentStep:+$('treatmentStep').value,targetPercentile:+$('targetPercentile').value,swi:+$('swi').value,sor:+$('sor').value,nw:+$('nw').value,no:+$('no').value,eorType:$('eorType').value,treatmentType:$('treatmentType').value}}
function smoothField(raw,p,passes){let a=raw.slice();for(let pass=0;pass<passes;pass++){const b=a.slice();for(let z=0;z<p.nz;z++)for(let y=0;y<p.ny;y++)for(let x=0;x<p.nx;x++){let sum=a[idx(x,y,z,p)]*2,w=2;for(const[dX,dY,dZ]of dirs){const X=x+dX,Y=y+dY,Z=z+dZ;if(X>=0&&Y>=0&&Z>=0&&X<p.nx&&Y<p.ny&&Z<p.nz){sum+=a[idx(X,Y,Z,p)];w++}}b[idx(x,y,z,p)]=sum/w}a=b}return a}
function makeGeology(p){const n=p.nx*p.ny*p.nz,raw=Array.from({length:n},()=>gaussian()),passes=Math.round(p.correlation*6),s=smoothField(raw,p,passes),cut=percentile(s,1-p.highPermFraction),k=s.map(v=>v>=cut?p.permContrast:1);for(let i=0;i<n;i++)k[i]*=Math.exp(.18*s[i]);return k}
function spanningCluster(k,p){const threshold=percentile(k,1-p.highPermFraction),active=k.map(v=>v>=threshold),seen=new Uint8Array(k.length),q=[];for(let z=0;z<p.nz;z++)for(let y=0;y<p.ny;y++){const i=idx(0,y,z,p);if(active[i]){seen[i]=1;q.push(i)}}for(let h=0;h<q.length;h++){const i=q[h],[x,y,z]=xyz(i,p);for(const[dX,dY,dZ]of dirs){const X=x+dX,Y=y+dY,Z=z+dZ;if(X<0||Y<0||Z<0||X>=p.nx||Y>=p.ny||Z>=p.nz)continue;const j=idx(X,Y,Z,p);if(active[j]&&!seen[j]){seen[j]=1;q.push(j)}}}let spans=false;for(let z=0;z<p.nz;z++)for(let y=0;y<p.ny;y++)if(seen[idx(p.nx-1,y,z,p)])spans=true;return{mask:seen,spans,threshold,frac:q.length/k.length}}
function processFactors(type){if(type==='polymer')return{mobility:.62,spread:1.05,oilGain:1.05};if(type==='co2')return{mobility:1.35,spread:1.12,oilGain:1.12};if(type==='foam')return{mobility:.52,spread:.95,oilGain:1.03};return{mobility:1,spread:1,oilGain:1}}
function relperm(sw,p){const den=Math.max(1-p.swi-p.sor,.05),se=clamp((sw-p.swi)/den,0,1),krw=Math.pow(se,p.nw),kro=Math.pow(1-se,p.no);return{se,krw,kro}}
function totalMob(sw,p,M){const r=relperm(sw,p);return r.kro+M*r.krw}
function pressureSolve(effK,sw,p,M,guess){const n=effK.length,P=guess?Float64Array.from(guess):new Float64Array(n);if(!guess)for(let i=0;i<n;i++){const[x]=xyz(i,p);P[i]=1-x/(p.nx-1)}for(let it=0;it<18;it++){const next=Float64Array.from(P);for(let z=0;z<p.nz;z++)for(let y=0;y<p.ny;y++)for(let x=1;x<p.nx-1;x++){const i=idx(x,y,z,p),li=totalMob(sw[i],p,M);let num=0,den=0;for(const[dX,dY,dZ]of dirs){const X=x+dX,Y=y+dY,Z=z+dZ;if(X<0||Y<0||Z<0||X>=p.nx||Y>=p.ny||Z>=p.nz)continue;const j=idx(X,Y,Z,p),lj=totalMob(sw[j],p,M),ki=effK[i]*li,kj=effK[j]*lj,T=2*ki*kj/Math.max(ki+kj,1e-12);num+=T*P[j];den+=T}if(den>0)next[i]=num/den}for(let z=0;z<p.nz;z++)for(let y=0;y<p.ny;y++){next[idx(0,y,z,p)]=1;next[idx(p.nx-1,y,z,p)]=0}P.set(next)}return P}
function run(){const p=params();if(p.swi+p.sor>=.9){alert('Swi + Sor must be below 0.90');return}const n=p.nx*p.ny*p.nz,k=makeGeology(p),perc=spanningCluster(k,p),sw=new Float32Array(n).fill(p.swi),treated=new Uint8Array(n),effK=Float64Array.from(k),pf=processFactors(p.eorType),M=p.mobilityRatio*pf.mobility,maxSw=1-p.sor;for(let z=0;z<p.nz;z++)for(let y=0;y<p.ny;y++)sw[idx(0,y,z,p)]=maxSw;
 const targetK=percentile(k,p.targetPercentile/100),history=[];let bt=null,pressure=null;
 for(let t=0;t<p.steps;t++){
   if(t===Math.min(p.treatmentStep,p.steps-1)&&p.treatmentType!=='none'){for(let i=0;i<n;i++){const r=relperm(sw[i],p);if(perc.mask[i]&&k[i]>=targetK&&r.se>.18){treated[i]=1;const tf=p.treatmentType==='foam'?.75:1;effK[i]*=Math.max(.02,1-p.treatmentStrength*tf)}}pressure=null}
   if(t%3===0||pressure===null)pressure=pressureSolve(effK,sw,p,M,pressure);
   const next=Float32Array.from(sw);let maxFlux=1e-12;const fluxes=[];
   for(let z=0;z<p.nz;z++)for(let y=0;y<p.ny;y++)for(let x=0;x<p.nx;x++){const i=idx(x,y,z,p),ri=relperm(sw[i],p);if(ri.se<=.002)continue;for(const[dX,dY,dZ]of dirs){const X=x+dX,Y=y+dY,Z=z+dZ;if(X<0||Y<0||Z<0||X>=p.nx||Y>=p.ny||Z>=p.nz)continue;const j=idx(X,Y,Z,p),dp=pressure[i]-pressure[j];if(dp<=0)continue;const li=totalMob(sw[i],p,M),lj=totalMob(sw[j],p,M),ki=effK[i]*li,kj=effK[j]*lj,T=2*ki*kj/Math.max(ki+kj,1e-12),q=T*dp;if(q>maxFlux)maxFlux=q;fluxes.push([i,j,q])}}
   for(const[i,j,q]of fluxes){const ri=relperm(sw[i],p);let prob=p.propagation*pf.spread*Math.pow(q/maxFlux,.45)*(.25+.9*ri.se);if(rng()<clamp(prob,0,.96)){const gain=(.05+.18*Math.pow(q/maxFlux,.35))*(maxSw-sw[j]);next[j]=Math.min(maxSw,Math.max(next[j],sw[j]+gain))}}
   sw.set(next);for(let z=0;z<p.nz;z++)for(let y=0;y<p.ny;y++)sw[idx(0,y,z,p)]=maxSw;
   let qTot=0,qWater=0;for(let z=0;z<p.nz;z++)for(let y=0;y<p.ny;y++){const i=idx(p.nx-1,y,z,p),j=idx(p.nx-2,y,z,p),r=relperm(sw[i],p),lamO=r.kro,lamW=M*r.krw,T=2*effK[i]*effK[j]/Math.max(effK[i]+effK[j],1e-12),q=T*Math.max(pressure[j]-pressure[i],0),fw=lamW/Math.max(lamO+lamW,1e-12);qTot+=q;qWater+=q*fw}
   const wc=qTot>0?qWater/qTot:0;if(bt===null&&wc>.10)bt=t;let rf=0,sweep=0;for(let i=0;i<n;i++){const r=relperm(sw[i],p);rf+=(sw[i]-p.swi)/Math.max(1-p.swi,1e-9);sweep+=r.se>.05?1:0}rf=clamp(rf/n,0,.95);sweep/=n;const qo=2200*pf.oilGain*qTot/Math.max(p.ny*p.nz,1)*(1-wc),qw=2200*qTot/Math.max(p.ny*p.nz,1)*wc;history.push({t,qo,qw,wc,rf,sweep})
 }
 latest={p,k,effK,sw,treated,perc,history,bt,pressure,M};render()}
function render3D(){if(!latest)return;const{p,k,sw,treated,perc}=latest,mode=$('viewMode').value,x=[],y=[],z=[],c=[],text=[],maxPoints=4200,skip=Math.max(1,Math.ceil(k.length/maxPoints));for(let i=0;i<k.length;i+=skip){let include=true,val=0;if(mode==='saturation'){val=sw[i];include=relperm(val,p).se>.03}else if(mode==='permeability')val=Math.log10(k[i]);else if(mode==='cluster'){val=perc.mask[i]?1:0;include=!!perc.mask[i]}else{val=treated[i]?1:0;include=!!treated[i]}if(!include)continue;const[X,Y,Z]=xyz(i,p);x.push(X);y.push(Y);z.push(Z);c.push(val);text.push(`x=${X}, y=${Y}, z=${Z}<br>k=${k[i].toFixed(1)} rel.<br>Sw=${sw[i].toFixed(2)}${treated[i]?'<br>Treated':''}`)}const colorscale=mode==='permeability'?'Viridis':mode==='saturation'?'Turbo':mode==='cluster'?'Blues':'Reds';Plotly.react('reservoir3d',[{type:'scatter3d',mode:'markers',x,y,z,text,hovertemplate:'%{text}<extra></extra>',marker:{size:4,color:c,colorscale,opacity:.72,colorbar:{title:mode}}}],{margin:{l:0,r:0,t:10,b:0},paper_bgcolor:'rgba(0,0,0,0)',plot_bgcolor:'rgba(0,0,0,0)',font:{color:'#dfe9f5'},scene:{xaxis:{title:'X / injector → producer'},yaxis:{title:'Y'},zaxis:{title:'Layer',autorange:'reversed'},aspectmode:'manual',aspectratio:{x:1.7,y:1,z:.55},bgcolor:'rgba(0,0,0,0)'}},{responsive:true})}
function renderProduction(){const h=latest.history,t=h.map(d=>d.t),qo=h.map(d=>d.qo),wc=h.map(d=>100*d.wc),rf=h.map(d=>100*d.rf);Plotly.react('productionPlot',[{x:t,y:qo,name:'Oil-rate index',type:'scatter',mode:'lines',line:{width:3}},{x:t,y:wc,name:'Water cut %',type:'scatter',mode:'lines',yaxis:'y2'},{x:t,y:rf,name:'Recovery factor %',type:'scatter',mode:'lines',yaxis:'y2',line:{dash:'dot'}}],{margin:{l:58,r:58,t:16,b:48},paper_bgcolor:'rgba(0,0,0,0)',plot_bgcolor:'rgba(0,0,0,0)',font:{color:'#dfe9f5'},xaxis:{title:'Simulation step',gridcolor:'#20344a'},yaxis:{title:'Relative rate index',gridcolor:'#20344a'},yaxis2:{title:'Percent',overlaying:'y',side:'right',range:[0,100]},legend:{orientation:'h',y:1.12}},{responsive:true})}
function render(){const l=latest,h=l.history,last=h[h.length-1];$('rfKpi').textContent=(last.rf*100).toFixed(1)+'%';$('wcKpi').textContent=(last.wc*100).toFixed(1)+'%';$('btKpi').textContent=l.bt===null?'No breakthrough':'Step '+l.bt;$('spanKpi').textContent=l.perc.spans?'Yes':'No';render3D();renderProduction();const treated=l.treated.reduce((a,b)=>a+b,0);const notes=[['Connectivity',l.perc.spans?`A spanning high-permeability path exists (${(100*l.perc.frac).toFixed(1)}% of cells connected from the injector side).`:'No injector-to-producer spanning high-permeability path was detected.'],['Physics',`Corey relperm is active with Swi=${l.p.swi.toFixed(2)}, Sor=${l.p.sor.toFixed(2)}, nw=${l.p.nw.toFixed(1)}, no=${l.p.no.toFixed(1)}. Pressure is solved iteratively and CA movement is weighted by positive Darcy-like flux.`],['Conformance',treated?`${treated} cells were treated at step ${l.p.treatmentStep}. The permeability change forces the pressure solution to redistribute subsequent flow.`:'No conformance treatment was applied.']];$('diagnostics').innerHTML=notes.map(([a,b])=>`<div class="insight"><b>${a}</b><p>${b}</p></div>`).join('')}
function wire(){const ranges={highPermFraction:'hpv',permContrast:'pcv',correlation:'scv',mobilityRatio:'mrv',propagation:'ppv',treatmentStrength:'tsv',treatmentStep:'tssv',targetPercentile:'ctv',swi:'swiv',sor:'sorv',nw:'nwv',no:'nov'};function labels(){for(const[k,v]of Object.entries(ranges)){let x=+$(k).value,s=x;if(k==='permContrast')s=x+'×';if(k==='treatmentStrength'||k==='targetPercentile')s=Math.round(x*(k==='treatmentStrength'?100:1))+'%';$(v).textContent=s}}Object.keys(ranges).forEach(k=>$(k).addEventListener('input',labels));$('runBtn').onclick=run;$('newGeoBtn').onclick=()=>{seed=(Date.now()>>>0);run()};$('viewMode').onchange=render3D;$('resetBtn').onclick=()=>{for(const[k,v]of Object.entries(defaults))if($(k))$(k).value=v;labels();seed=137;run()};labels();run()}
wire();
