const $ = id => document.getElementById(id);
const defaults={nx:20,ny:20,nz:8,steps:90,highPermFraction:.38,permContrast:12,correlation:.62,mobilityRatio:2,propagation:.64,treatmentStrength:.65,treatmentStep:28,targetPercentile:82,eorType:'polymer',treatmentType:'gel'};
let seed=137, latest=null;
const dirs=[[1,0,0],[-1,0,0],[0,1,0],[0,-1,0],[0,0,1],[0,0,-1]];
function rng(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296}
function gaussian(){let u=Math.max(rng(),1e-9),v=rng();return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v)}
function idx(x,y,z,p){return x+p.nx*(y+p.ny*z)}
function xyz(i,p){const z=Math.floor(i/(p.nx*p.ny)),r=i-z*p.nx*p.ny,y=Math.floor(r/p.nx),x=r-y*p.nx;return[x,y,z]}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function percentile(a,q){const s=[...a].sort((x,y)=>x-y),i=Math.floor(clamp(q,0,1)*(s.length-1));return s[i]}
function params(){return{nx:+$('nx').value,ny:+$('ny').value,nz:+$('nz').value,steps:+$('steps').value,highPermFraction:+$('highPermFraction').value,permContrast:+$('permContrast').value,correlation:+$('correlation').value,mobilityRatio:+$('mobilityRatio').value,propagation:+$('propagation').value,treatmentStrength:+$('treatmentStrength').value,treatmentStep:+$('treatmentStep').value,targetPercentile:+$('targetPercentile').value,eorType:$('eorType').value,treatmentType:$('treatmentType').value}}
function smoothField(raw,p,passes){let a=raw.slice();for(let pass=0;pass<passes;pass++){let b=a.slice();for(let z=0;z<p.nz;z++)for(let y=0;y<p.ny;y++)for(let x=0;x<p.nx;x++){let sum=a[idx(x,y,z,p)]*2,w=2;for(const[dX,dY,dZ]of dirs){const X=x+dX,Y=y+dY,Z=z+dZ;if(X>=0&&Y>=0&&Z>=0&&X<p.nx&&Y<p.ny&&Z<p.nz){sum+=a[idx(X,Y,Z,p)];w++}}b[idx(x,y,z,p)]=sum/w}a=b}return a}
function makeGeology(p){const n=p.nx*p.ny*p.nz,raw=Array.from({length:n},()=>gaussian()),passes=Math.round(p.correlation*6),s=smoothField(raw,p,passes),cut=percentile(s,1-p.highPermFraction),k=s.map(v=>v>=cut?p.permContrast:1);for(let i=0;i<n;i++)k[i]*=Math.exp(.18*s[i]);return k}
function spanningCluster(k,p){const threshold=percentile(k,1-p.highPermFraction),active=k.map(v=>v>=threshold),seen=new Uint8Array(k.length),q=[];for(let z=0;z<p.nz;z++)for(let y=0;y<p.ny;y++){let i=idx(0,y,z,p);if(active[i]){seen[i]=1;q.push(i)}}for(let h=0;h<q.length;h++){let i=q[h],[x,y,z]=xyz(i,p);for(const[dX,dY,dZ]of dirs){let X=x+dX,Y=y+dY,Z=z+dZ;if(X<0||Y<0||Z<0||X>=p.nx||Y>=p.ny||Z>=p.nz)continue;let j=idx(X,Y,Z,p);if(active[j]&&!seen[j]){seen[j]=1;q.push(j)}}}let spans=false;for(let z=0;z<p.nz;z++)for(let y=0;y<p.ny;y++)if(seen[idx(p.nx-1,y,z,p)])spans=true;return{mask:seen,spans,threshold,frac:q.length/k.length}}
function processFactors(type){if(type==='polymer')return{mobility:.62,spread:1.08,oilGain:1.12};if(type==='co2')return{mobility:1.35,spread:1.18,oilGain:1.22};if(type==='foam')return{mobility:.52,spread:.95,oilGain:1.10};return{mobility:1,spread:1,oilGain:1}}
function run(){const p=params(),n=p.nx*p.ny*p.nz,k=makeGeology(p),perc=spanningCluster(k,p),sat=new Float32Array(n),treated=new Uint8Array(n),effK=Float64Array.from(k),pf=processFactors(p.eorType),M=p.mobilityRatio*pf.mobility;for(let z=0;z<p.nz;z++)for(let y=0;y<p.ny;y++)sat[idx(0,y,z,p)]=1;
 const targetK=percentile(k,p.targetPercentile/100),history=[],breakthrough=null;let bt=null,cumOil=0,ooip=n*.22*.68;
 for(let t=0;t<p.steps;t++){
   if(t===Math.min(p.treatmentStep,p.steps-1)&&p.treatmentType!=='none'){
     for(let i=0;i<n;i++)if(perc.mask[i]&&k[i]>=targetK&&sat[i]>.18){treated[i]=1;const typeFactor=p.treatmentType==='foam'?.75:1;effK[i]*=(1-p.treatmentStrength*typeFactor)}
   }
   const next=Float32Array.from(sat);
   for(let z=0;z<p.nz;z++)for(let y=0;y<p.ny;y++)for(let x=0;x<p.nx;x++){
     const i=idx(x,y,z,p);if(sat[i]<=.005)continue;
     for(const[dX,dY,dZ]of dirs){const X=x+dX,Y=y+dY,Z=z+dZ;if(X<0||Y<0||Z<0||X>=p.nx||Y>=p.ny||Z>=p.nz)continue;const j=idx(X,Y,Z,p);if(sat[j]>=.995)continue;const trans=2*effK[i]*effK[j]/Math.max(effK[i]+effK[j],1e-9);const bias=dX===1?1.34:dX===-1?.45:1;const visc=1/(1+.35*Math.max(M-1,0));const channel=Math.pow(trans/Math.max(p.permContrast,1),.35);let prob=p.propagation*pf.spread*bias*visc*(.55+.75*channel);prob*=.3+.9*sat[i];if(rng()<clamp(prob,0,.98)){const gain=.12+.28*clamp(channel,0,1);next[j]=Math.max(next[j],clamp(sat[j]+gain*(1-sat[j]),0,1))}}
   }
   for(let i=0;i<n;i++)sat[i]=Math.max(sat[i]*.995,next[i]);for(let z=0;z<p.nz;z++)for(let y=0;y<p.ny;y++)sat[idx(0,y,z,p)]=1;
   let prodSat=0,prodK=0;for(let z=0;z<p.nz;z++)for(let y=0;y<p.ny;y++){const i=idx(p.nx-1,y,z,p);prodSat+=sat[i];prodK+=effK[i]}
   prodSat/=p.ny*p.nz;prodK/=p.ny*p.nz;if(bt===null&&prodSat>.12)bt=t;
   let swept=0,oilMob=0;for(let i=0;i<n;i++){swept+=sat[i];oilMob+=(1-sat[i])*(.2+.8*Math.min(effK[i]/p.permContrast,1))}swept/=n;oilMob/=n;
   const wc=clamp(prodSat*(M/(1+M))+.08*swept,0,.995),qo=Math.max(0,1800*pf.oilGain*oilMob*(1-wc*.45)*(perc.spans?1.08:.88)),qw=qo*wc/Math.max(1-wc,.03);cumOil+=qo;const rf=clamp(cumOil/(ooip*9000),0,.85);history.push({t,qo,qw,wc,rf,swept})
 }
 latest={p,k,effK,sat,treated,perc,history,bt};render();
}
function render3D(){if(!latest)return;const{p,k,sat,treated,perc}=latest,mode=$('viewMode').value,x=[],y=[],z=[],c=[],text=[];const maxPoints=4200,skip=Math.max(1,Math.ceil(k.length/maxPoints));for(let i=0;i<k.length;i+=skip){let include=true,val=0;if(mode==='saturation'){val=sat[i];include=val>.05}else if(mode==='permeability'){val=Math.log10(k[i]);include=true}else if(mode==='cluster'){val=perc.mask[i]?1:0;include=!!perc.mask[i]}else{val=treated[i]?1:0;include=!!treated[i]}if(!include)continue;const[X,Y,Z]=xyz(i,p);x.push(X);y.push(Y);z.push(Z);c.push(val);text.push(`x=${X}, y=${Y}, z=${Z}<br>k=${k[i].toFixed(1)} rel.<br>S=${sat[i].toFixed(2)}${treated[i]?'<br>Treated':''}`)}
 const colorscale=mode==='permeability'?'Viridis':mode==='saturation'?'Turbo':mode==='cluster'?'Blues':'Reds';Plotly.react('reservoir3d',[{type:'scatter3d',mode:'markers',x,y,z,text,hovertemplate:'%{text}<extra></extra>',marker:{size:4,color:c,colorscale,opacity:.72,colorbar:{title:mode}}}],{margin:{l:0,r:0,t:10,b:0},paper_bgcolor:'rgba(0,0,0,0)',plot_bgcolor:'rgba(0,0,0,0)',font:{color:'#dfe9f5'},scene:{xaxis:{title:'X / injector → producer'},yaxis:{title:'Y'},zaxis:{title:'Layer',autorange:'reversed'},aspectmode:'manual',aspectratio:{x:1.7,y:1,z:.55},bgcolor:'rgba(0,0,0,0)'}},{responsive:true})}
function renderProduction(){const h=latest.history,t=h.map(d=>d.t),qo=h.map(d=>d.qo),wc=h.map(d=>100*d.wc),rf=h.map(d=>100*d.rf);Plotly.react('productionPlot',[{x:t,y:qo,name:'Oil rate',type:'scatter',mode:'lines',line:{width:3}},{x:t,y:wc,name:'Water cut %',type:'scatter',mode:'lines',yaxis:'y2'},{x:t,y:rf,name:'Recovery factor %',type:'scatter',mode:'lines',yaxis:'y2',line:{dash:'dot'}}],{margin:{l:58,r:58,t:16,b:48},paper_bgcolor:'rgba(0,0,0,0)',plot_bgcolor:'rgba(0,0,0,0)',font:{color:'#dfe9f5'},xaxis:{title:'Simulation step',gridcolor:'#20344a'},yaxis:{title:'Oil rate (relative field units)',gridcolor:'#20344a'},yaxis2:{title:'Percent',overlaying:'y',side:'right',range:[0,100]},legend:{orientation:'h',y:1.12}},{responsive:true})}
function render(){const l=latest,h=l.history,last=h[h.length-1];$('rfKpi').textContent=(last.rf*100).toFixed(1)+'%';$('wcKpi').textContent=(last.wc*100).toFixed(1)+'%';$('btKpi').textContent=l.bt===null?'No breakthrough':'Step '+l.bt;$('spanKpi').textContent=l.perc.spans?'Yes':'No';render3D();renderProduction();const treated=l.treated.reduce((a,b)=>a+b,0),m=l.p.mobilityRatio*processFactors(l.p.eorType).mobility;let notes=[['Connectivity',l.perc.spans?`A spanning high-permeability path exists (${(100*l.perc.frac).toFixed(1)}% of cells connected from injector side), increasing early breakthrough risk.`:`No spanning high-permeability path was detected; displacement must cross lower-permeability barriers.`],['Mobility',m>1?`Effective mobility ratio is ${m.toFixed(2)} (>1), so viscous instability and channeling are favored.`:`Effective mobility ratio is ${m.toFixed(2)} (≤1), improving displacement stability and areal/vertical sweep.`],['Conformance',treated?`${treated} high-flow cells were selectively treated. Their transmissibility was reduced after step ${l.p.treatmentStep}, redirecting subsequent CA growth.`:'No conformance cells were treated; the flood follows the original connectivity architecture.']];$('diagnostics').innerHTML=notes.map(([a,b])=>`<div class="insight"><b>${a}</b><p>${b}</p></div>`).join('')}
function wire(){const ranges={highPermFraction:'hpv',permContrast:'pcv',correlation:'scv',mobilityRatio:'mrv',propagation:'ppv',treatmentStrength:'tsv',treatmentStep:'tssv',targetPercentile:'ctv'};function labels(){for(const[k,v]of Object.entries(ranges)){let x=+$(k).value,s=x;if(k==='permContrast')s=x+'×';if(k==='treatmentStrength'||k==='targetPercentile')s=Math.round(x*(k==='treatmentStrength'?100:1))+'%';$(v).textContent=s}}Object.keys(ranges).forEach(k=>$(k).addEventListener('input',labels));$('runBtn').onclick=run;$('newGeoBtn').onclick=()=>{seed=(Date.now()>>>0);run()};$('viewMode').onchange=render3D;$('resetBtn').onclick=()=>{for(const[k,v]of Object.entries(defaults))if($(k))$(k).value=v;labels();seed=137;run()};labels();run()}
wire();
